config/routes.rb
PairWithWin::Application.routes.draw do

  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base

  def top_post_in_7_days
    where(dfsf)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.order('point desc')
  end

  def update
    p = Post.find(params[:id])
    if params[:plus] == "true"
      p.point = p.point + 1
    elsif params[:minus] == "true"
      p.point = p.point - 1
    end
    p.save
    redirect_to posts_path
  end

  def destroy
    p = Post.find(params[:id])
    p.destroy
    redirect_to posts_path
  end

  def new
    @post = Post.new
  end

  def create
    Post.create(title: params[:post][:title], description: params[:post][:description], point: 0)
    redirect_to posts_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PairWithWin</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h3><%= link_to 'New Post', new_post_path %></h3>
<% @posts.each do |p| %>
  <ul>
    <li><%= link_to '+', post_path(id: p.id, plus: true), method: :put %></li>
    <li><%= link_to '-', post_path(id: p.id, minus:true),  method: :put %></li>
    <li><%= p.title %></li>
    <li><%= p.description %></li>
    <li><%= link_to 'destroy', post_path(id: p.id), method: :delete %></li>
  </ul>
<% end %>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <%= f.submit :create %>
<% end %>